FROM mcr.microsoft.com/devcontainers/java:1-21-bullseye

ARG MAVEN_MAJOR_VERSION=3
ARG MAVEN_VESRION=3.9.6

RUN apt-get -y update
RUN apt-get install --no-install-recommends git ca-certificates curl zip unzip
RUN apt-get -y upgrade --no-install-recommends
RUN apt-get autoremove -y

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip "awscliv2.zip"
RUN ./aws/install
RUN rm -rf ./aws awscliv2.zip

RUN rm -rf /var/lib/apt/lists/*

RUN curl -L https://dlcdn.apache.org/maven/maven-3/${MAVEN_VESRION}/binaries/apache-maven-${MAVEN_VESRION}-bin.tar.gz | tar xz -C /opt

USER vscode
ENV PATH=${PATH}:/opt/apache-maven-${MAVEN_VESRION}/bin